version: '3.7'

services:
  db:
    image: mysql:8.0
    ports: 
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: delivereat
      MYSQL_USER: delivereat
      MYSQL_PASSWORD: delivereat